[settings]
not_found_auto_install = true
python_venv_auto_create = true
trusted_config_paths = ["~/Workspace/tgautier"]

[tools]
deno = "2.6.10"
elixir = "1.19.5-otp-28"
erlang = "28.3.2"
go = "1.26.0"
helm = "4.1.1"
node = "24"
python = "3.14.3"
ruby = "4.0.1"
yarn = "4.12.0"
